[supabase]
url = "https://dwopbzbjrhnfkwewtwuy.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR3b3BiemJqcmhuZmt3ZXd0d3V5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAyMjM3OTEsImV4cCI6MjA4NTc5OTc5MX0.YvE89i7wmdudQ079gQEhdbA7ajZglLc7rGvdRyeJoLE"
